// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxwjnfeyrqoxvfjwnuqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4d2puZmV5cnFveHZmandudXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Mzc0NDQsImV4cCI6MjA2NjUxMzQ0NH0.ovFUiMXs4RE3q6JvH7eeGTtXiJn7Mb61aDhbLd6ff2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);