// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsdwdikztkjflnqpgrng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzZHdkaWt6dGtqZmxucXBncm5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MjI5NDgsImV4cCI6MjA2NjQ5ODk0OH0.cWtme__HcM6LCPoenwbQ27v2Rizpvfv9e2cHZp_OpgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);